# zhiyan-auth-service
server:
  port: 8091

spring:
  application:
    name: zhiyan-auth-service

  cloud:
    nacos:
      # Nacos服务发现
      discovery:
        # Nacos地址
        server-addr: 127.0.0.1:8848
        # 命名空间
        namespace: zhiyan-dev
        # 组
        group: DEFAULT_GROUP
        # 权重
        weight: 1

      # Nacos配置中心
      config:
        # 和服务发现的一样
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: ${spring.cloud.nacos.discovery.group}
        file-extension: yaml

    # OpenFeign配置
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: basic
      compression:
        request:
          enabled: true
        response:
          enabled: true

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/zhiyan_platform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:zjm10086}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      pool-name: AuthServiceHikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  data:
    # Redis配置
    redis:
      # Redis服务器地址，默认本地,端口，默认6379
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:zjm10086}
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USERNAME:your-email@qq.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

  # Jackson配置
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  # JPA配置 - 新增配置解决方言问题
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

# 验证码配置
app:
  verification-code:
    length: 6
    expire-minutes: 10
    rate-limit-minutes: 1
    enable-database-storage: true
    enable-email-sending: true
    enable-cleanup-task: true
    max-retry-attempts: 3
  name: 智研平台

# JWT配置
jwt:
  secret: zhiyan-platform-secret-key-2024
  issuer: zhiyan-platform
  access-token-expire-minutes: 120
  refresh-token-expire-minutes: 10080

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    git:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# 日志配置
logging:
  level:
    root: INFO
    hbnu.project.zhiyan: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: INFO
    # 关闭特定框架的冗余日志
    org.springframework.data.redis.repository: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/zhiyan-auth-service.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30