# 服务器配置
server:
  # 网关服务监听端口
  port: 9005

# Spring相关配置
spring:
  main:
    web-application-type: reactive  # 关键配置：声明为响应式 Web 应用
  config:
    import: nacos:zhiyan-gateway.yaml
  # 应用信息配置
  application:
    # 应用名称，用于服务注册与发现
    name: zhiyan-gateway

  # 云服务相关配置
  cloud:
    # Nacos配置中心与服务发现配置
    nacos:
      discovery:
        # Nacos服务注册中心地址
        server-addr: 127.0.0.1:8848
        # Nacos命名空间，用于环境隔离
        namespace: zhiyan-dev
        group: DEFAULT_GROUP

    # Spring Cloud Gateway配置
    gateway:
      # 服务发现配置
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能
          enabled: true
          # 使用小写服务名，默认是大写
          lower-case-service-id: true


# 日志配置
logging:
  level:
    # 配置Spring Cloud Gateway的日志级别为DEBUG
    org.springframework.cloud.gateway: debug
    # 配置Netty HTTP客户端的日志级别为DEBUG
    reactor.netty.http.client: debug

# 应用监控配置
management:
  endpoints:
    web:
      exposure:
        # 暴露所有监控端点
        include: '*'
  endpoint:
    health:
      # 健康检查端点显示详细信息
      show-details: always